# Generated by Django 4.1.6 on 2023-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="description_as_markdown",
            field=models.BooleanField(default=False, verbose_name="As markdown"),
        ),
    ]
