# Generated by Django 4.1.6 on 2023-02-22 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_courses_description_as_markdown"),
        ("mainapp", "0003_data_migration"),
    ]

    operations = []
